[package]
name = "fltk-term"
version = "0.1.4"
edition = "2021"
description = "A minimal terminal widget for fltk"
repository = "https://github.com/fltk-rs/fltk-term"
documentation = "https://docs.rs/fltk-term"
keywords = ["gui", "ui", "widgets", "bindings", "graphics"]
categories = ["gui"]
readme = "README.md"
license = "MIT"

[dependencies]
portable-pty =  "0.8"
fltk = { version = "1.5", optional = true }
fltk2 = { version = "0.1", optional = true }

[features]
default = ["fltk"]
debug-term = []
